### ISSUE TITLE
Just a heads Up: Will not be compatible with cms v3.0.5 without changes

### ISSUE THREAD

**Issue by mkoistinen** [aldryn/aldryn-segmentation#3]
NOTICE: This commit here: https://github.com/divio/django-cms/commit/d8b36f21ec64128c715ccbeb198b41557a686b2a#diff-2e3d5c25dd6236e9f360d8a2fcfffaec

Changes the signature to get_processors to: `get_processors(self, context, plugin, placeholder)`
This will require changes in this code.

Further recall that once Aldryn reaches 3.0.3, the local version of get_processors should be removed in favor of calling the one in the render_plugin superclass anyway.

**Comment by petrklus** [comment]
Is this still the case @mkoistinen ? Wondering if anyone is using this with latest Django CMS

**Comment by mkoistinen** [comment]
I'm pretty sure we're using this with the latest django CMS 3.2.x, so, I think I'll close this.
